### ISSUE TITLE
It won't print any message

### ISSUE THREAD

**Issue by lrn2prgrm** [masasron/IPConfig.js#1]
I try to run it on the browser but I get no answer (it doesn't seem designed to work in node). It doesn't print anything at all.

**Comment by masasron** [comment]
Hi @lrn2prgrm, sorry this script was built for the web and not node, but since we talking here is how to do it in node.

```js
require('dns').lookup(require('os').hostname(), function (err, add, fam) {
    console.log('addr: '+add);
})
```
